"""Interactions contract: the ``ask_user`` human-in-the-loop surface.

``models`` holds the durable request/state and validated response pydantic
models, the ``SuspendedInteraction`` sentinel an async ask returns, the
``AnswerFormat`` enum, and the display-only ``MediaItem``/``MediaKind`` media
models a question may carry; ``asker`` holds the ``AskUser`` callable Protocol
the engine-agnostic helper satisfies and the ``check_ask_timing`` guard;
``continuation`` holds the generic driver-continuation context an async ask reads,
plus the adopt-or-chain guard a caller applies to a returned park sentinel and the
chained-park vocabulary a caller that parks on a nested CALL composes its binding from.
"""

from __future__ import annotations

from tai42_contract.interactions.asker import AskUser, check_ask_timing
from tai42_contract.interactions.continuation import (
    CHAINED_PARK_CONTEXT_KEY,
    CHAINED_PARK_KEY_PREFIX,
    CHAINED_PARK_TOKEN_KEY,
    EXPIRY_ANSWER,
    PARK_COMPLETION_FAILED,
    PARK_COMPLETION_REPARKED,
    PARK_COMPLETION_SUCCEEDED,
    PARK_COMPLETION_THREAD_KEY,
    SUSPENDED_INTERACTION_MARKER_KEY,
    NestedParkOwnershipError,
    assert_park_adoptable,
    attach_chained_park,
    bound_execution_identity_for_fire,
    chained_park_claims,
    chained_park_context,
    current_execution_identity,
    fire_continuation_abandoned,
    get_park_completion,
    get_resume_continuation_tool,
    is_chained_park_key,
    new_chained_park_key,
    read_suspended_interaction_marker,
    register_continuation_abandonment_handler,
    register_execution_identity_accessor,
    register_execution_identity_binder,
    repark_notice,
    reset_park_completion,
    reset_resume_continuation_tool,
    resolve_park_adoption,
    set_park_completion,
    set_resume_continuation_tool,
    suspended_interaction_marker,
)
from tai42_contract.interactions.models import (
    FILE_MEDIA_KINDS,
    LOCATION_ADDRESS_MAX_CHARS,
    LOCATION_NAME_MAX_CHARS,
    MEDIA_CAPTION_MAX_CHARS,
    MEDIA_DATA_URI_MAX_CHARS,
    MEDIA_FILENAME_MAX_CHARS,
    MEDIA_MAX_ITEMS,
    MEDIA_ROUTE_PREFIX,
    MEDIA_TOTAL_URI_CHARS,
    MEDIA_URL_MAX_CHARS,
    MISMATCH_NOTICE_MAX_CHARS,
    AnswerFormat,
    AnswerMismatchPolicy,
    InteractionRequest,
    InteractionResponse,
    InteractionState,
    LocationElement,
    MediaItem,
    MediaKind,
    SuspendedInteraction,
    check_media_list,
    served_media_id,
    validate_action_url,
)

__all__ = [
    "CHAINED_PARK_CONTEXT_KEY",
    "CHAINED_PARK_KEY_PREFIX",
    "CHAINED_PARK_TOKEN_KEY",
    "EXPIRY_ANSWER",
    "FILE_MEDIA_KINDS",
    "LOCATION_ADDRESS_MAX_CHARS",
    "LOCATION_NAME_MAX_CHARS",
    "MEDIA_CAPTION_MAX_CHARS",
    "MEDIA_DATA_URI_MAX_CHARS",
    "MEDIA_FILENAME_MAX_CHARS",
    "MEDIA_MAX_ITEMS",
    "MEDIA_ROUTE_PREFIX",
    "MEDIA_TOTAL_URI_CHARS",
    "MEDIA_URL_MAX_CHARS",
    "MISMATCH_NOTICE_MAX_CHARS",
    "PARK_COMPLETION_FAILED",
    "PARK_COMPLETION_REPARKED",
    "PARK_COMPLETION_SUCCEEDED",
    "PARK_COMPLETION_THREAD_KEY",
    "SUSPENDED_INTERACTION_MARKER_KEY",
    "AnswerFormat",
    "AnswerMismatchPolicy",
    "AskUser",
    "InteractionRequest",
    "InteractionResponse",
    "InteractionState",
    "LocationElement",
    "MediaItem",
    "MediaKind",
    "NestedParkOwnershipError",
    "SuspendedInteraction",
    "assert_park_adoptable",
    "attach_chained_park",
    "bound_execution_identity_for_fire",
    "chained_park_claims",
    "chained_park_context",
    "check_ask_timing",
    "check_media_list",
    "current_execution_identity",
    "fire_continuation_abandoned",
    "get_park_completion",
    "get_resume_continuation_tool",
    "is_chained_park_key",
    "new_chained_park_key",
    "read_suspended_interaction_marker",
    "register_continuation_abandonment_handler",
    "register_execution_identity_accessor",
    "register_execution_identity_binder",
    "repark_notice",
    "reset_park_completion",
    "reset_resume_continuation_tool",
    "resolve_park_adoption",
    "served_media_id",
    "set_park_completion",
    "set_resume_continuation_tool",
    "suspended_interaction_marker",
    "validate_action_url",
]
