"""Vendor-neutral monitoring contract.

Generic across LLM-observability backends, modeled on OpenTelemetry span
semantics, cost/tokens/input/output optional, write/read as separate
capabilities so emit-only backends still fit. Concrete backends are implemented
elsewhere; this contract names and assumes none.
"""

from __future__ import annotations

from tai42_contract.monitoring.errors import (
    MonitoringError,
    MonitoringReadNotSupportedError,
    ObservationNotFoundError,
    PayloadRefUnresolvedError,
    TraceNotFoundError,
)
from tai42_contract.monitoring.models import (
    DEFAULT_LEVEL,
    GENERATION_MESSAGE_METADATA_KEY,
    PAYLOAD_REF_KEY,
    PROMOTED_METADATA_KEYS,
    RESERVED_KEY_PREFIX,
    STEP_ROLE_METADATA_KEY,
    TIMING_ABSENT,
    TIMING_METADATA_KEY,
    TRACE_PREVIEW_MAX_CHARS,
    UNRECORDED_KEY,
    Dimension,
    Measure,
    MetricsCapability,
    MetricsQuery,
    MetricsResult,
    MetricsRow,
    MonitoringExportHealth,
    MonitoringFilter,
    MonitoringLevel,
    MonitoringObservation,
    MonitoringTrace,
    MonitoringTraceSummary,
    OrderBy,
    PayloadRef,
    RecordId,
    RunAttribution,
    Span,
    SpanKind,
    SpanWindowItem,
    StepRole,
    TokenUsage,
    TraceContext,
    preview,
)
from tai42_contract.monitoring.monitoring import Monitoring
from tai42_contract.monitoring.reader import MonitoringReader
from tai42_contract.monitoring.trace_context_carrier import (
    MONITORING_PARENT_SPAN_ID_KEY,
    MONITORING_TRACE_ID_KEY,
    ambient_trace_context,
    get_ambient_trace_context,
    reset_ambient_trace_context,
    set_ambient_trace_context,
)
from tai42_contract.monitoring.writer import (
    RUN_ATTRIBUTION_TRACE_NAME,
    RUN_VERSION_METADATA_KEY,
    MonitoringWriter,
    attribute_run,
)

__all__ = [
    "DEFAULT_LEVEL",
    "GENERATION_MESSAGE_METADATA_KEY",
    "MONITORING_PARENT_SPAN_ID_KEY",
    "MONITORING_TRACE_ID_KEY",
    "PAYLOAD_REF_KEY",
    "PROMOTED_METADATA_KEYS",
    "RESERVED_KEY_PREFIX",
    "RUN_ATTRIBUTION_TRACE_NAME",
    "RUN_VERSION_METADATA_KEY",
    "STEP_ROLE_METADATA_KEY",
    "TIMING_ABSENT",
    "TIMING_METADATA_KEY",
    "TRACE_PREVIEW_MAX_CHARS",
    "UNRECORDED_KEY",
    "Dimension",
    "Measure",
    "MetricsCapability",
    "MetricsQuery",
    "MetricsResult",
    "MetricsRow",
    "Monitoring",
    "MonitoringError",
    "MonitoringExportHealth",
    "MonitoringFilter",
    "MonitoringLevel",
    "MonitoringObservation",
    "MonitoringReadNotSupportedError",
    "MonitoringReader",
    "MonitoringTrace",
    "MonitoringTraceSummary",
    "MonitoringWriter",
    "ObservationNotFoundError",
    "OrderBy",
    "PayloadRef",
    "PayloadRefUnresolvedError",
    "RecordId",
    "RunAttribution",
    "Span",
    "SpanKind",
    "SpanWindowItem",
    "StepRole",
    "TokenUsage",
    "TraceContext",
    "TraceNotFoundError",
    "ambient_trace_context",
    "attribute_run",
    "get_ambient_trace_context",
    "preview",
    "reset_ambient_trace_context",
    "set_ambient_trace_context",
]
