"""Typed builders for the manifest and feature-env of each stack profile."""

from __future__ import annotations

from tai42_e2e.manifests.agents import (
    build_agent_async_park_stack,
    build_agent_route_park_stack,
    build_agents_redis_stack,
    build_agents_stack,
)
from tai42_e2e.manifests.auth import (
    _KEYS_BOOTSTRAP_TOKEN,
    build_accounts_stack,
    build_auth_stack,
    build_keys_bootstrap_stack,
    build_oidc_stack,
)
from tai42_e2e.manifests.bridge import (
    BRIDGE_MAX_CONCURRENT_TURNS,
    BRIDGE_PER_ADDRESS_TURNS_PER_HOUR,
    BRIDGE_SYNC_DOOR_WAIT_SECONDS,
    BRIDGE_TWILIO_ACCOUNT_SID,
    BRIDGE_TWILIO_CLIENT,
    BRIDGE_TWILIO_CLIENT_B,
    BRIDGE_TWILIO_FROM,
    BRIDGE_TWILIO_FROM_B,
    BRIDGE_WHATSAPP_CLIENT,
    BRIDGE_WHATSAPP_PHONE_ID,
    BRIDGE_WHATSAPP_PHONE_ID_B,
    BRIDGE_WHATSAPP_PHONE_ID_C,
    BRIDGE_WHATSAPP_WABA_ID,
    build_bridge_stack,
)
from tai42_e2e.manifests.channels import (
    SLACK_ALLOWED_RECIPIENTS,
    SLACK_BOT_USER_ID,
    SLACK_DEFAULT_RECIPIENT,
    SLACK_UNLISTED_RECIPIENT,
    TELEGRAM_ALLOWED_RECIPIENTS,
    TELEGRAM_DEFAULT_RECIPIENT,
    TELEGRAM_UNLISTED_RECIPIENT,
    TWILIO_ALLOWED_RECIPIENTS,
    TWILIO_DEFAULT_RECIPIENT,
    TWILIO_FROM,
    TWILIO_UNLISTED_RECIPIENT,
    WEB_IDENTITY,
    WEB_MAX_ANSWER_RESTORES,
    WEB_MAX_BODY_BYTES,
    WEB_MAX_STREAMS_PER_VISITOR,
    build_channel_stack,
)
from tai42_e2e.manifests.connectors import (
    ATLASSIAN_CLIENT_ID,
    GITHUB_CLIENT_ID,
    GOOGLE_CLIENT_ID,
    SLACK_CLIENT_ID,
    build_connectors_stack,
    build_shipped_connectors_stack,
)
from tai42_e2e.manifests.core import (
    build_async_park_stack,
    build_bare_stack,
    build_core_stack,
    build_embed_stack,
    build_minimal_stack,
    build_recycle_stack,
    build_replicas_stack,
)
from tai42_e2e.manifests.extensions import build_extensions_stack
from tai42_e2e.manifests.feature_env import _base_env, _llm_env, _memory_agent_state_env, _redis_feature_env
from tai42_e2e.manifests.manifest_mcp import (
    POSTGRES_MCP_PROBE_ROW_NAME,
    POSTGRES_MCP_PROBE_SCHEMA,
    POSTGRES_MCP_PROBE_TABLE,
    POSTGRES_MCP_TITLE,
    RESILIENCE_MCP_TITLE,
    build_postgres_mcp_stack,
    build_resilience_mcp_stack,
    postgres_mcp_tool_name,
    resilience_mcp_tool_name,
)
from tai42_e2e.manifests.marketplace import (
    build_marketplace_authz_stack,
    build_marketplace_connectors_stack,
    build_marketplace_prefix_stack,
    build_marketplace_quarantine_stack,
    build_marketplace_stack,
)
from tai42_e2e.manifests.monitoring import build_monitoring_stack
from tai42_e2e.manifests.off import build_off_stack
from tai42_e2e.manifests.projection import build_projection_authz_stack, build_projection_stack
from tai42_e2e.manifests.routers import build_api_router_stack, build_default_router_stack, build_router_merge_stack
from tai42_e2e.manifests.sandbox import (
    _DEEP_AGENT_ENTRY,
    build_claude_agent_stack,
    build_deep_agent_durable_stack,
    build_sandbox_local_claude_stack,
    build_sandbox_local_deep_stack,
    build_sandbox_local_stack,
    build_sandbox_stack,
)
from tai42_e2e.manifests.scheduling import build_schedule_stack
from tai42_e2e.manifests.seams import build_seams_seed_off_stack, build_seams_seed_stack, build_seams_stack
from tai42_e2e.manifests.stripe import _STRIPE_TEST_SECRET_KEY, build_stripe_stack
from tai42_e2e.manifests.studio import build_studio_stack
from tai42_e2e.manifests.tool_entries import (
    _CORE_ROUTERS,
    _EXTENSION_MODULES,
    _PROJECTED_API_TOOLS,
    PROBE_TOOLS_TITLE,
    _builtin_entries,
    _probe_tools_entry,
    _toolbox_tools_entry,
)

__all__ = [
    "ATLASSIAN_CLIENT_ID",
    "BRIDGE_MAX_CONCURRENT_TURNS",
    "BRIDGE_PER_ADDRESS_TURNS_PER_HOUR",
    "BRIDGE_SYNC_DOOR_WAIT_SECONDS",
    "BRIDGE_TWILIO_ACCOUNT_SID",
    "BRIDGE_TWILIO_CLIENT",
    "BRIDGE_TWILIO_CLIENT_B",
    "BRIDGE_TWILIO_FROM",
    "BRIDGE_TWILIO_FROM_B",
    "BRIDGE_WHATSAPP_CLIENT",
    "BRIDGE_WHATSAPP_PHONE_ID",
    "BRIDGE_WHATSAPP_PHONE_ID_B",
    "BRIDGE_WHATSAPP_PHONE_ID_C",
    "BRIDGE_WHATSAPP_WABA_ID",
    "GITHUB_CLIENT_ID",
    "GOOGLE_CLIENT_ID",
    "POSTGRES_MCP_PROBE_ROW_NAME",
    "POSTGRES_MCP_PROBE_SCHEMA",
    "POSTGRES_MCP_PROBE_TABLE",
    "POSTGRES_MCP_TITLE",
    "PROBE_TOOLS_TITLE",
    "RESILIENCE_MCP_TITLE",
    "SLACK_ALLOWED_RECIPIENTS",
    "SLACK_BOT_USER_ID",
    "SLACK_CLIENT_ID",
    "SLACK_DEFAULT_RECIPIENT",
    "SLACK_UNLISTED_RECIPIENT",
    "TELEGRAM_ALLOWED_RECIPIENTS",
    "TELEGRAM_DEFAULT_RECIPIENT",
    "TELEGRAM_UNLISTED_RECIPIENT",
    "TWILIO_ALLOWED_RECIPIENTS",
    "TWILIO_DEFAULT_RECIPIENT",
    "TWILIO_FROM",
    "TWILIO_UNLISTED_RECIPIENT",
    "WEB_IDENTITY",
    "WEB_MAX_ANSWER_RESTORES",
    "WEB_MAX_BODY_BYTES",
    "WEB_MAX_STREAMS_PER_VISITOR",
    "_CORE_ROUTERS",
    "_DEEP_AGENT_ENTRY",
    "_EXTENSION_MODULES",
    "_KEYS_BOOTSTRAP_TOKEN",
    "_PROJECTED_API_TOOLS",
    "_STRIPE_TEST_SECRET_KEY",
    "_base_env",
    "_builtin_entries",
    "_llm_env",
    "_memory_agent_state_env",
    "_probe_tools_entry",
    "_redis_feature_env",
    "_toolbox_tools_entry",
    "build_accounts_stack",
    "build_agent_async_park_stack",
    "build_agent_route_park_stack",
    "build_agents_redis_stack",
    "build_agents_stack",
    "build_api_router_stack",
    "build_async_park_stack",
    "build_auth_stack",
    "build_bare_stack",
    "build_bridge_stack",
    "build_channel_stack",
    "build_claude_agent_stack",
    "build_connectors_stack",
    "build_core_stack",
    "build_deep_agent_durable_stack",
    "build_default_router_stack",
    "build_embed_stack",
    "build_extensions_stack",
    "build_keys_bootstrap_stack",
    "build_marketplace_authz_stack",
    "build_marketplace_connectors_stack",
    "build_marketplace_prefix_stack",
    "build_marketplace_quarantine_stack",
    "build_marketplace_stack",
    "build_minimal_stack",
    "build_monitoring_stack",
    "build_off_stack",
    "build_oidc_stack",
    "build_postgres_mcp_stack",
    "build_projection_authz_stack",
    "build_projection_stack",
    "build_recycle_stack",
    "build_replicas_stack",
    "build_resilience_mcp_stack",
    "build_router_merge_stack",
    "build_sandbox_local_claude_stack",
    "build_sandbox_local_deep_stack",
    "build_sandbox_local_stack",
    "build_sandbox_stack",
    "build_schedule_stack",
    "build_seams_seed_off_stack",
    "build_seams_seed_stack",
    "build_seams_stack",
    "build_shipped_connectors_stack",
    "build_stripe_stack",
    "build_studio_stack",
    "postgres_mcp_tool_name",
    "resilience_mcp_tool_name",
]
