"""The subject-keyed state store contract: the wire models, the typed errors, and
the callable seams a consumer registers on the ``app.states`` facet.

The facet Protocol itself lives with the other app facets
(:class:`~tai42_contract.app.facets.AppStates`); this package holds the data
shapes and errors that facet passes across the door-agnostic seam.
"""

from __future__ import annotations

from tai42_contract.states.errors import (
    DeclarationInUseError,
    InvalidPathError,
    MigrationConversionError,
    ModuleExistsError,
    ModuleInUseError,
    ModuleValidationError,
    MountConflictError,
    NarrowingRequiresConfirmationError,
    NonAdditiveRedeclareError,
    RegimeViolationError,
    SchemaValidationError,
    StateExistsError,
    StateNotFoundError,
    StatesError,
    StatesNotConfiguredError,
    SubjectFoldError,
    SubjectRefusedError,
    ValueValidationError,
)
from tai42_contract.states.models import (
    KEY_MAX_CHARS,
    MAX_RETENTION_DAYS,
    MODULE_NAME_RE,
    PERSON_KIND,
    STATE_NAME_RE,
    SUBJECT_KIND_RE,
    ApplyResult,
    CompletedOrigin,
    ConsumerLink,
    ConsumerLister,
    ConsumerRow,
    MountBody,
    MountValidator,
    RecordView,
    StateContext,
    StateDeclaration,
    StateDoor,
    StateModuleDocument,
    StateSubject,
    SubjectCandidates,
    WriteEntry,
    WriteOrigin,
    WritesPage,
)
from tai42_contract.states.ops import (
    APPEND,
    KEYED_OPS,
    MAX_OPS_PER_BATCH,
    MAX_PATH_SEGMENTS,
    MAX_REMOVE_KEYS,
    OPS,
    json_equal,
    keyed_op_match_counts,
    validate_guard,
    validate_op,
    validate_path,
    value_at_path,
)

__all__ = [
    "APPEND",
    "KEYED_OPS",
    "KEY_MAX_CHARS",
    "MAX_OPS_PER_BATCH",
    "MAX_PATH_SEGMENTS",
    "MAX_REMOVE_KEYS",
    "MAX_RETENTION_DAYS",
    "MODULE_NAME_RE",
    "OPS",
    "PERSON_KIND",
    "STATE_NAME_RE",
    "SUBJECT_KIND_RE",
    "ApplyResult",
    "CompletedOrigin",
    "ConsumerLink",
    "ConsumerLister",
    "ConsumerRow",
    "DeclarationInUseError",
    "InvalidPathError",
    "MigrationConversionError",
    "ModuleExistsError",
    "ModuleInUseError",
    "ModuleValidationError",
    "MountBody",
    "MountConflictError",
    "MountValidator",
    "NarrowingRequiresConfirmationError",
    "NonAdditiveRedeclareError",
    "RecordView",
    "RegimeViolationError",
    "SchemaValidationError",
    "StateContext",
    "StateDeclaration",
    "StateDoor",
    "StateExistsError",
    "StateModuleDocument",
    "StateNotFoundError",
    "StateSubject",
    "StatesError",
    "StatesNotConfiguredError",
    "SubjectCandidates",
    "SubjectFoldError",
    "SubjectRefusedError",
    "ValueValidationError",
    "WriteEntry",
    "WriteOrigin",
    "WritesPage",
    "json_equal",
    "keyed_op_match_counts",
    "validate_guard",
    "validate_op",
    "validate_path",
    "value_at_path",
]
