"""The subject-keyed state store contract: the wire models, the typed errors, and
the callable seams a consumer registers on the ``app.states`` facet.

The facet Protocol itself lives with the other app facets
(:class:`~tai42_contract.app.facets.AppStates`); this package holds the data
shapes and errors that facet passes across the door-agnostic seam.
"""

from __future__ import annotations

from tai42_contract.states.binding import (
    StateAttach,
    StateBinding,
    StateInjection,
    StateUpdate,
)
from tai42_contract.states.errors import (
    AttachConflictError,
    DeclarationInUseError,
    InvalidPathError,
    NonAdditiveRedeclareError,
    RegimeViolationError,
    SchemaValidationError,
    StateExistsError,
    StateNotFoundError,
    StatesError,
    StatesNotConfiguredError,
    SubjectFoldError,
    SubjectRefusedError,
    TemplateExistsError,
    TemplateInUseError,
    TemplateValidationError,
    ValueValidationError,
)
from tai42_contract.states.models import (
    KEY_MAX_CHARS,
    MAX_RETENTION_DAYS,
    PERSON_KIND,
    STATE_NAME_RE,
    SUBJECT_KIND_RE,
    TEMPLATE_NAME_RE,
    ApplyResult,
    AttachBody,
    AttachReconcileContext,
    AttachReconciler,
    AttachReconcileRecords,
    AttachValidator,
    CompletedOrigin,
    ConsumerLink,
    ConsumerLister,
    ConsumerRow,
    StateContext,
    StateDeclaration,
    StateDoor,
    StateRecord,
    StateSubject,
    StateTemplateDeclarations,
    StateTemplateDocument,
    StateTemplateJq,
    StateTemplateReconcile,
    SubjectCandidates,
    TemplateJqApplyResult,
    TemplateJqResult,
    WriteEntry,
    WriteOrigin,
    WritesPage,
)
from tai42_contract.states.ops import (
    APPEND,
    KEYED_OPS,
    MAX_OPS_PER_BATCH,
    MAX_PATH_SEGMENTS,
    MAX_REMOVE_KEYS,
    OPS,
    json_equal,
    keyed_op_match_counts,
    validate_guard,
    validate_op,
    validate_path,
    value_at_path,
)

__all__ = [
    "APPEND",
    "KEYED_OPS",
    "KEY_MAX_CHARS",
    "MAX_OPS_PER_BATCH",
    "MAX_PATH_SEGMENTS",
    "MAX_REMOVE_KEYS",
    "MAX_RETENTION_DAYS",
    "OPS",
    "PERSON_KIND",
    "STATE_NAME_RE",
    "SUBJECT_KIND_RE",
    "TEMPLATE_NAME_RE",
    "ApplyResult",
    "AttachBody",
    "AttachConflictError",
    "AttachReconcileContext",
    "AttachReconcileRecords",
    "AttachReconciler",
    "AttachValidator",
    "CompletedOrigin",
    "ConsumerLink",
    "ConsumerLister",
    "ConsumerRow",
    "DeclarationInUseError",
    "InvalidPathError",
    "NonAdditiveRedeclareError",
    "RegimeViolationError",
    "SchemaValidationError",
    "StateAttach",
    "StateBinding",
    "StateContext",
    "StateDeclaration",
    "StateDoor",
    "StateExistsError",
    "StateInjection",
    "StateNotFoundError",
    "StateRecord",
    "StateSubject",
    "StateTemplateDeclarations",
    "StateTemplateDocument",
    "StateTemplateJq",
    "StateTemplateReconcile",
    "StateUpdate",
    "StatesError",
    "StatesNotConfiguredError",
    "SubjectCandidates",
    "SubjectFoldError",
    "SubjectRefusedError",
    "TemplateExistsError",
    "TemplateInUseError",
    "TemplateJqApplyResult",
    "TemplateJqResult",
    "TemplateValidationError",
    "ValueValidationError",
    "WriteEntry",
    "WriteOrigin",
    "WritesPage",
    "json_equal",
    "keyed_op_match_counts",
    "validate_guard",
    "validate_op",
    "validate_path",
    "value_at_path",
]
